bg_speedmultiply(0, 2, true, true)
bg_speedmultiply(1, 2, true, true)
bg_speedmultiply(2, 2, true, true)
bg_speedmultiply(3, 2, true, true)
bg_speedmultiply(4, 2, true, true)
bg_speedmultiply(5, 2, true, true)
bg_speedmultiply(6, 2, true, true)
bg_speedmultiply(7, 2, true, true)