max_obj = 5
obj_name[0] = "Spawn"
obj_index[0] = obj_spawn
obj_sprite[0] = spr_player_idle
obj_depth[0] = -50
obj_name[1] = "Wall [0]"
obj_index[1] = obj_wall1_classic
obj_sprite[1] = spr_wall1_classic
obj_depth[1] = 0
obj_name[2] = "Wall [1]"
obj_index[2] = obj_wall2_classic
obj_sprite[2] = spr_wall2_classic
obj_depth[2] = 0
obj_name[3] = "Wall [0] (Medieval)"
obj_index[3] = obj_wall1_medieval
obj_sprite[3] = spr_wall1_medieval
obj_depth[3] = 0
obj_name[4] = "Wall [1] (Medieval)"
obj_index[4] = obj_wall2_medieval
obj_sprite[4] = spr_wall2_medieval
obj_depth[4] = 0
obj_name[5] = "Wall [0] (Cavern)"
obj_index[5] = obj_wall1_cavern
obj_sprite[5] = spr_wall1_cavern
obj_depth[5] = 0
obj_name[6] = "Wall [1] (Cavern)"
obj_index[6] = obj_wall2_cavern
obj_sprite[6] = spr_wall2_cavern
obj_depth[6] = 0
obj_name[7] = "Wall (Freezer)"
obj_index[7] = obj_wall_freezer
obj_sprite[7] = spr_wall_freezer
obj_depth[7] = 0
obj_name[8] = "Win"
obj_index[8] = obj_win
obj_sprite[8] = spr_win
obj_depth[8] = 0
obj_name[9] = "Hurt"
obj_index[9] = obj_hurt
obj_sprite[9] = spr_hurt
obj_depth[9] = 0